### ISSUE TITLE
BUG: panic: dev_api_endpoints_requests" is not a valid metric name

### ISSUE THREAD

**Issue by Sergey1011010** [RedHatInsights/insights-results-aggregator#954]
```
panic: descriptor Desc{fqName: "aggregator-dev_api_endpoints_requests", help: "The total number of requests per endpoint", constLabels: {}, variableLabels: [endpoint]} is invalid: "aggregator-dev_api_endpoints_requests" is not a valid metric name

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0000a12c0, 0xc000310230, 0x1, 0x1)
        /home/szakharo/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:401 +0xad
github.com/prometheus/client_golang/prometheus/promauto.Factory.NewCounterVec(0x121ee80, 0xc0000a12c0, 0xc0002f38c0, 0xe, 0x0, 0x0, 0xf9b1a9, 0x16, 0xfb2f41, 0x29, ...)
        /home/szakharo/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promauto/auto.go:276 +0x118
github.com/prometheus/client_golang/prometheus/promauto.NewCounterVec(...)
        /home/szakharo/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promauto/auto.go:176
github.com/RedHatInsights/insights-operator-utils/metrics.AddAPIMetricsWithNamespace(0xc0002f38c0, 0xe)
        /home/szakharo/go/pkg/mod/github.com/!red!hat!insights/insights-operator-utils@v1.4.0/metrics/metrics.go:60 +0x232
github.com/RedHatInsights/insights-results-aggregator/metrics.AddMetricsWithNamespace(0xc0002f38c0, 0xe)
        /home/szakharo/projects/aggregator/insights-results-aggregator/metrics/metrics.go:110 +0x50
main.startService(0xc200000000000000)
        /home/szakharo/projects/aggregator/insights-results-aggregator/aggregator.go:219 +0x207
main.handleCommand(0xf93130, 0xd, 0x0)
        /home/szakharo/projects/aggregator/insights-results-aggregator/aggregator.go:501 +0x26d
main.main()
        /home/szakharo/projects/aggregator/insights-results-aggregator/aggregator.go:487 +0x186

```

**Comment by joselsegura** [comment]
A question about the reproduction of this bug: have you used the metrics namespace? In that case, which value did you use?

**Comment by Sergey1011010** [comment]
@joselsegura I used the default config-devel, but I actually changed it here https://github.com/RedHatInsights/insights-results-aggregator/pull/955/files so it isn't reproduced by the default config anymore, maybe we need to close it.

**Comment by joselsegura** [comment]
Oh, I didn't realize that I introduce a faulty name there... Thank you for fixing!
